/**:
  ros__parameters:
    min_longitudinal_offset: 3.95
    max_longitudinal_offset: 4.25 
    min_lateral_offset: -0.97
    max_lateral_offset: 0.97
    min_height_offset: 1.05
    max_height_offset: 1.55
