/**:
  ros__parameters:
    wheel_radius: 0.341 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.153 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.544 # between front wheel center and rear wheel center
    wheel_tread: 1.45 # between left wheel center and right wheel center
    front_overhang: 1.12 # between front wheel center and vehicle front
    rear_overhang: 0.82 # between rear wheel center and vehicle rear
    left_overhang: 0.18 # between left wheel center and vehicle left
    right_overhang: 0.18 # between right wheel center and vehicle right
    vehicle_height: 2.40
    max_steer_angle: 0.70 # [rad]
